global:
  scrape_interval: 10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'python_exporter'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'Metrics_prom'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'mqtt_exporter'
    static_configs:
      - targets: ['mqtt_exporter:9000']
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9001']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

rule_files:
  - "alert_rules.yml"


